Cv tables
dashakots/homeworks pull request #4
Opened 2024-12-12 13:40 UTC by dashakots

create two documents : cv.html and style.html

2024-12-12 14:44 UTC, mhasilau requested changes

2024-12-12 14:44 UTC, mhasilau commented on cv.html
> +            <td bgcolor="darkgray"><i><strong>Личная информация</strong></i></td>
поубирай инлайн стили

2024-12-12 14:44 UTC, mhasilau commented on cv.html
> +            <td bgcolor="darkgray"><i><strong>Иностранные языки</strong></i></td>
инлайн

2024-12-12 14:44 UTC, mhasilau commented on cv.html
> +            <td bgcolor="darkgray"><i><strong>Контактная информация</strong></i></td>
инлайн

2024-12-12 14:44 UTC, mhasilau commented on cv.html
> +            <td bgcolor="darkgray"><i><strong>Личные качества</strong></i></td>
инлайн

2024-12-12 14:44 UTC, mhasilau commented on index_lists.html
> +</html>
ок

2024-12-12 14:44 UTC, mhasilau commented on style.html
> +    <div><span>●</span><span class="underline" style="font-size: 200%;">Home</span></div>
убери инлайн и сделай это списком

2024-12-12 16:25 UTC, dashakots commented on style.html
> +    <div><span>●</span><span class="underline" style="font-size: 200%;">Home</span></div>
вроде бы все исправила

2024-12-12 19:08 UTC, dashakots commented on cv.html
> +            <td bgcolor="darkgray"><i><strong>Личные качества</strong></i></td>
Готово

2024-12-12 19:08 UTC, dashakots commented on cv.html
> +            <td bgcolor="darkgray"><i><strong>Контактная информация</strong></i></td>
Done

2024-12-12 19:09 UTC, dashakots commented on cv.html
> +            <td bgcolor="darkgray"><i><strong>Иностранные языки</strong></i></td>
Готово

2024-12-13 07:09 UTC, mhasilau approved these changes

2024-12-15 12:51 UTC, merged